using System;

//entry class, this class will be responsible of each entry that the user enter
public class Entry
{
    //declaring variables that'll be use on my class

    //_prompt variable I'll use to catch the random prompt generated by my promp generator
    public string _prompt;

    //prompt to display to the user
    public string _displayEntry;

    //I need the current date, to do that I called datetime.now I parsed it to a string
    //and I told in what format I want my date    
    public string _date = DateTime.Now.ToString("M/d/yyyy");

    //_entry variable will hold the user entry 
    public string _entry;

    //entry class need to connect with prompgenerator class because I need the prompt
    //for both of my methods (Store/EntryDisp) then to be able to do it I create a 
    //PrompGenerator object
    public PrompGenerator _randomPrompt = new PrompGenerator();

    //In this variable i'll store user entry with date and prompt together
    //with a special format in order to recover them later when user uses load method
    public string _storeEntry;

    //Store method to store user entry with date and prompt
    public void Store(){
        _entry = _entry.Replace("," , "~");
        _storeEntry = $"{_date},{_prompt},{_entry}";
    }

    //EntryDisp method to display user entry
    public void EntryDisp(){
        _displayEntry = _entry.Replace("~" , ",");
        Console.WriteLine($"Date: {_date} - Prompt: {_prompt}\n{_displayEntry}");
    }

}